wandb_version: 1

vocab_size:
  desc: null
  value: 99963
max_len:
  desc: null
  value: 64
embed_dim:
  desc: null
  value: 128
rnn_units:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.3
batch_size:
  desc: null
  value: 128
lr:
  desc: null
  value: 0.0003
architecture:
  desc: null
  value: BiGRU + AttentionPooling
monitor:
  desc: null
  value: val_AUC-PR
_wandb:
  desc: null
  value:
    python_version: 3.10.19
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1762861734.0
    t:
      1:
      - 2
      - 3
      - 5
      - 49
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 49
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.10.19
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
